//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsriaqWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class rq_operaciones
    {
        public long ID_Operacion { get; set; }
        public long ID_Usuario { get; set; }
        public string nombre { get; set; }
        public string agentequimicooperacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> seleccionfrasesH { get; set; }
        public Nullable<short> noaplicafrasesHcheck { get; set; }
        public Nullable<short> seleccionVLAED { get; set; }
        public Nullable<short> seleccionVLAEDmatpar { get; set; }
        public Nullable<short> seleccionVLAEDparticulada { get; set; }
        public Nullable<short> seleccionVLAEDnoparticulada { get; set; }
        public Nullable<short> seleccionsustanciacomercialsino { get; set; }
        public Nullable<short> seleccionmaterialesnosujetosanormativa { get; set; }
        public string frasesHseleccionadas { get; set; }
        public Nullable<short> clasepeligro { get; set; }
        public Nullable<short> seleccioncantidaddia { get; set; }
        public Nullable<short> clasecantidaddia { get; set; }
        public Nullable<short> selecciontipofrecuenciautilizacion { get; set; }
        public Nullable<short> seleccionfrecuenciautilizacion { get; set; }
        public Nullable<short> clasefrecuenciautilizacion { get; set; }
        public Nullable<short> claseexposicionpotencial { get; set; }
        public Nullable<short> claseriesgopotencial { get; set; }
        public Nullable<short> puntuacionriesgopotencial { get; set; }
        public Nullable<short> seleccionestadovolpul { get; set; }
        public Nullable<short> seleccionvolatilidadpulverulenciasolido { get; set; }
        public Nullable<short> clasevolatilidadpulverulenciasolido { get; set; }
        public Nullable<short> tempusovolatilidadpulverulencialiquido { get; set; }
        public Nullable<short> tempebullicionvolatilidadpulverulencialiquido { get; set; }
        public Nullable<short> clasevolatilidadpulverulenciaLiquido { get; set; }
        public Nullable<short> seleccionvolatilidadpulverulenciasolvapsolido { get; set; }
        public Nullable<short> clasevolatilidadpulverulenciasolvapsolido { get; set; }
        public Nullable<short> seleccionvolatilidadpulverulenciasolvapliquido { get; set; }
        public Nullable<short> clasevolatilidadpulverulenciasolvapliquido { get; set; }
        public Nullable<short> clasevolatilidadvulverulencia { get; set; }
        public Nullable<short> puntuacionvolatilidadvulverulencia { get; set; }
        public Nullable<short> seleccionprocedimientotrabajo { get; set; }
        public Nullable<short> claseprocedimientotrabajo { get; set; }
        public Nullable<short> puntuacionprocedimientotrabajo { get; set; }
        public Nullable<short> seleccionproteccionescolectivas { get; set; }
        public Nullable<short> claseproteccionescolectivas { get; set; }
        public Nullable<short> puntuacionproteccionescolectivas { get; set; }
        public Nullable<short> seleccionvla { get; set; }
        public Nullable<short> puntuacionvla { get; set; }
        public Nullable<long> puntuacionriesgoporinhalacion { get; set; }
        public Nullable<short> prioridadaccion { get; set; }
    }
}
