//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsriaqWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int ID_Usuario { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Fecha_creacion { get; set; }
    }
}
